language: c

os:
  - linux

addons:
  apt:
    packages:
      - gcc-4.6

branches:
  only:
    - master
    - ubuntu12.04amd64

before_script:
  - git clone git://git.openwrt.org/15.05/openwrt.git
  - cd chaos_calmer
  - make menuconfig
  - make
  - export PATH=$PATH:$PWD/staging_dir/host/bin:$PWD/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin

script:
  - cd Tunet
  - ./autogen-cross-compile.sh
  - make



